[package]
name = "mackerel_client"
version = "0.0.1"
authors = ["itchyny <itchyny@hatena.ne.jp>"]
description = "An API client library for Mackerel"
repository = "https://github.com/itchyny/mackerel-client-rs"
documentation = "https://itchyny.github.io/mackerel-client-rs/mackerel_client/"
readme = "README.md"
license = "MIT"
keywords = ["api", "mackerel"]
categories = ["api-bindings"]

[dependencies]
hyper = "0.11.2"
hyper-tls = "0.1.2"
hyper-native-tls = "0.2.4"
serde = "1.0.12"
serde_derive = "1.0.12"
serde_json = "1.0.3"
error-chain = "0.11.0"
