[package]
name = "mackerel_client"
version = "0.0.1"
authors = ["itchyny <itchyny@hatena.ne.jp>"]
description = "An API client library for Mackerel"
repository = "https://github.com/itchyny/mackerel-client-rs"
documentation = "https://itchyny.github.io/mackerel-client-rs/mackerel_client/"
readme = "README.md"
license = "MIT"
keywords = ["api", "mackerel"]
categories = ["api-bindings"]

[dependencies]
url = "1.4.0"
tokio-core = "0.1"
hyper = "0.11.2"
hyper-tls = "0.1.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
error-chain = "0.11.0"
